### ISSUE TITLE
form is missing when I build the example

### ISSUE THREAD

**Issue by eruca** [duan602728596/antd-schema-form#13]
antd 3.21.4
antd-schema-form 3.0.1

```bash
import SchemaForm
Property 'form' is missing in type '{ json: { id: string; type: string; title: string; description: string; properties: { string: { id: string; type: string; title: string; description: string; properties: { default: { id: string; type: string; title: string; description: string; }; ... 15 more ...; oneOf: { ...; }; }; required: string[]; dependencies...' but required in type 'SchemaFormProps'.ts(2741)
Form.d.ts(165, 5): 'form' is declared here.
```

**Comment by duan602728596** [comment]
I tried it. I didn't reproduce this error. What is the version of your `typescript` and `antd`? May be related to the two versions.

**Comment by eruca** [comment]
typescript 3.6.3
antd 3.21.4

reproduce in the codesandbox
https://codesandbox.io/s/react-typescript-082u0?fontsize=14

**Comment by duan602728596** [comment]
I looked at your code, the code is running normally, and there is no problem with you.

**Comment by eruca** [comment]
Ok, but the typescript lint found some problems

**Comment by duan602728596** [comment]
Because of the version dependency, there may be some minor problems.

**Comment by eruca** [comment]
Thanks
