### ISSUE TITLE
Help: How to change the form layout?

### ISSUE THREAD

**Issue by rahulpsd18** [duan602728596/antd-schema-form#15]
I am unable to change the layout of the form. 
As seen in the screenshot below, the long text for label _"A super long name for boolean"_ is cut off.
![from](https://user-images.githubusercontent.com/14837582/69313964-f973e980-0c58-11ea-9151-810df212d945.PNG)

**Maybe we could have a way to pass our own `labelCol` and `wrapperCol` props to `SchemaForm` which it forwards to the `FormObject` [here](https://github.com/duan602728596/antd-schema-form/blob/f642954756de45d55cfa115fb5eecfd78c2dea44/src/SchemaForm.tsx#L67).** 

If this can be achieved then we could pass other props too, to make the component fully customizable to the extent `<Form/>` component already does.

---

Also, any suggestion on how to have a radio or checkbox with default value **and disabled too**? 
I can set a default value but can't disable it. 

Use case: I want the user to know the value of the checkbox/radio but not allow him to change it.

Thanks!

**Comment by duan602728596** [comment]
This modification takes a little time.
Style, you can temporarily override css.
Checkbox and radio, you can replace the default component with a custom component.

**Comment by rahulpsd18** [comment]
Ok, thanks! Will do it this way for now. 

It will be easier to just pass the props as we do with `antd` component so I will look into implementing the above feature myself when I get time.

**Comment by duan602728596** [comment]
Features have been added, see `$disabled` and `$formItemProps` for [Attributes](https://github.com/duan602728596/antd-schema-form/blob/master/docs/json_schema_configuration.md#attributes).
