### ISSUE TITLE
Error on 'getFieldProps with valid name string'

### ISSUE THREAD

**Issue by azro352** [duan602728596/antd-schema-form#17]
Hi

Would you mind explain the difference between the official jsonschema definition and the definition you use ?

I tried you librarie using an example from https://json-schema.org/learn/miscellaneous-examples.html (last one on fruits/vegetables), when I click on the main dropdown it raises `Uncaught Error: Must call `getFieldProps` with valid name string!`, I fixed it by adding ids to both properties to end with the following

```
    "properties": {
        "fruits": {
            "id": "fruits",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "vegetables": {
            "id": "vegetables",
            "type": "array",
            "items": {"$ref": "#/definitions/veggie"}
        }
    },
```
so why it there an `id` to add ? 

Then, now I'm getting the error when clicking on the button *Adding data* : what are the other différences to add to get it work with you lib ? 

Thanks

**Comment by duan602728596** [comment]
The role of id is to ensure that the value of the object type when the form is submitted can be formatted into the value configured by schemajson through the id; or the value of the object in the array can be obtained in the array.

Your form is configured in this way:

```json
{
  "id": "$root",
  "type": "object",
  "title": "$root",
  "properties": {
    "fruits": {
      "id": "$root/properties/fruits",
      "type": "array",
      "title": "fruits",
      "items": {
        "id": "$root/properties/fruits/items",
        "type": "string",
        "title": "fruit"
      }
    },
    "vegetables": {
      "id": "$root/properties/vegetables",
      "type": "array",
      "title": "vegetables",
      "items": {
        "id": "$root/properties/vegetables/items",
        "type": "string",
        "title": "vegetable"
      }
    }
  }
}
```

You can try to configure the form at https://duan602728596.github.io/antd-schema-form/#/CreateForm.

**Comment by azro352** [comment]
Ok for this, and how do you handle the `definitions` and `$ref` keys ? I can't get it work from the same schema (fruits/vegetables) because vegetables is an objet with properties, and put it in definitions allow to reuse again in another place

**Comment by duan602728596** [comment]
Sorry, this is not supported yet.
