### ISSUE TITLE
在添加可选项时，界面不会刷新

### ISSUE THREAD

**Issue by tempao3** [duan602728596/antd-schema-form#19]
只有第一次添加时会刷新，之后添加就不刷新了。

![image](https://user-images.githubusercontent.com/61924958/78851993-cf776400-7a4d-11ea-8539-767303821767.png)

在自己生成的表单里，给对象数组类型添加值时，界面也不会刷新。

**Comment by duan602728596** [comment]
确实，数据加上了，但是界面没刷新，得修复一下

**Comment by duan602728596** [comment]
已经修复，v4.0.0版本

**Comment by tempao3** [comment]
> 已经修复，v4.0.0版本

感谢~~~求更新到你的 demo 页面

**Comment by duan602728596** [comment]
> > 已经修复，v4.0.0版本
> 
> 感谢~~~求更新到你的 demo 页面

demo也已经更新了
