### ISSUE TITLE
Disable Collapsable Form

### ISSUE THREAD

**Issue by 1devNdogs** [duan602728596/antd-schema-form#21]
Hi, nice work here bro, I am reading the package implementation, and look pretty strong, I forked and implemented a custom file upload component with some AWS S3 features, and it works!, but I can't remove the Collapse Effect from SchemaForm, it seems to be wrapped by a Collapse Panel in the package implementation. I can replace the Collapse with a div or fragment, rebuild package, local install, .... and works very well, but have to build the package again for that, is there any way to disable Collapse from a prop or something??? to not modify the package, sorry the simple question, I am quite new in ant design and JSON schema.

**Comment by duan602728596** [comment]
You can configure customComponent like this, this is how to customize components,
```javascript
const customComponent = {
  defaultObject(root, form, element) {
    return <div>{ element }</div>
  }
};

 <SchemaForm customComponent={ customComponent } />
```
[Code reference](https://github.com/duan602728596/antd-schema-form/blob/master/src/components/custom/custom.tsx#L131)
