### ISSUE TITLE
请问如何动态改变input中的值?

### ISSUE THREAD

**Issue by wszdhxh** [duan602728596/antd-schema-form#24]
我想要实现通过改变select的值, 在调用select的onChange方法后将input中的值更改.
![image](https://user-images.githubusercontent.com/69642580/108682776-b2476900-752b-11eb-8471-51be5be7fb81.png)
上方的是select, 在选择后input中显示不同的描述

**Comment by duan602728596** [comment]
配置formOptions的onValuesChange判断组件值的变化，并通过ref获取到form并调用form.setFieldsValue修改值。
或者自定义组件内会有form，调用form.setFieldsValue修改值。

**Comment by wszdhxh** [comment]
![image](https://user-images.githubusercontent.com/69642580/108701941-8f28b380-7543-11eb-95db-af6bbef9ee80.png)
![image](https://user-images.githubusercontent.com/69642580/108701960-96e85800-7543-11eb-83e5-bd5a251229cf.png)
![image](https://user-images.githubusercontent.com/69642580/108702099-c008e880-7543-11eb-8d74-4f700c183b49.png)
![image](https://user-images.githubusercontent.com/69642580/108702532-5b01c280-7544-11eb-8385-5a613a47a4a2.png)
我添加了formOption后可以动态更改值了, 但是原本的输入框(名称的那个)没有值了, 删除formOption后才有显示, 我应该将所有输入框都用自定义组件代替吗?

**Comment by wszdhxh** [comment]
![image](https://user-images.githubusercontent.com/69642580/108707142-930c0400-754a-11eb-9300-514d7b520b8c.png)
![image](https://user-images.githubusercontent.com/69642580/108707216-ab7c1e80-754a-11eb-88fc-9a511cca07a2.png)
添加formOption后表格中也没有值

**Comment by duan602728596** [comment]
```javascript
<SchemaForm ref={ formRef }
  formOptions={{
    onValuesChange(c, a) {
      const key = 'key';

      if ((key in c) && c[key] === 'a') {
        formRef.current.setFieldsValue({
          changeKey: '12'
        });
      }
    }
  }}
/>
```
是这样处理的

**Comment by wszdhxh** [comment]
![image](https://user-images.githubusercontent.com/69642580/108799042-4700a400-75ca-11eb-8bef-49657a3d92dd.png)
![image](https://user-images.githubusercontent.com/69642580/108799076-5f70be80-75ca-11eb-9e74-db8248ae82e3.png)
![image](https://user-images.githubusercontent.com/69642580/108799059-541d9300-75ca-11eb-9187-c320195fea5d.png)
![image](https://user-images.githubusercontent.com/69642580/108799137-7fa07d80-75ca-11eb-8665-2b12997e4c1e.png)
![image](https://user-images.githubusercontent.com/69642580/108799216-b24a7600-75ca-11eb-8a6e-b044ae6a4fb0.png)
使用以上方法确实可以动态改变, 但是仍然无法显示在表格中

**Comment by duan602728596** [comment]
id和key没有对上，比如
description的id为`$root/properties/params/items/properties/description`而不是`$root/properties/params/items/properties/des`

**Comment by wszdhxh** [comment]
原来如此, 十分感谢大佬
