### ISSUE TITLE
Hi folk, does it support the config to remove the collapse pane of the form border? 

### ISSUE THREAD

**Issue by jacob2733** [duan602728596/antd-schema-form#26]
![image](https://user-images.githubusercontent.com/46584808/113984181-67847500-987d-11eb-83ef-33d4cb7f3086.png)

**Comment by duan602728596** [comment]
You can configure a custom object component like this: https://github.com/duan602728596/antd-schema-form/blob/master/docs/custom_rendering_component.md#custom-rendering-component. The default component name of object is called [`defaultObject`](https://github.com/duan602728596/antd-schema-form/blob/master/src/customComponent.ts#L32).
 
Actually, I don't know which style is more suitable, so I can only choose the folding panel.

**Comment by jacob2733** [comment]
yes!!thanks I figured it out. 
`const customComponent = {
    objectCustom(item, form, element) {
      return <div>{element}</div>;
    },
  };
customComponent={customComponent} 
$componentType: 'objectCustom',
`

**Comment by jacob2733** [comment]
BTW, one more question,  is there any quick config to put onOk button to the right position?

**Comment by duan602728596** [comment]
You can configure footer props, footer is function.

You can get the value you want like [this](https://github.com/duan602728596/antd-schema-form/blob/master/src/components/FormObject/FormObject.tsx#L143), and the function used here has been exported. 

By passing in ref, you can get the `form`.
