### ISSUE TITLE
required seems not work for tags component 

### ISSUE THREAD

**Issue by jacob2733** [duan602728596/antd-schema-form#27]
` "gender": {
      "id": "$root/properties/gender",
      "type": "array",
      "title": "性别",
      "description": "请选择性别",
      "$componentType": "tags",
      "$required": true
    },`
![image](https://user-images.githubusercontent.com/46584808/113985962-4ae93c80-987f-11eb-85db-3e003fc15ad7.png)

**Comment by duan602728596** [comment]
Because the array is not required, the minimum number of arrays can be verified with `minItems`.

**Comment by duan602728596** [comment]
It seems that you can consider adding the required verification of the array.

**Comment by jacob2733** [comment]
Okay, got it. Thanks!
