### ISSUE TITLE
How to set layout horizonal to make label and input in one line?

### ISSUE THREAD

**Issue by jacob2733** [duan602728596/antd-schema-form#28]
If possible, can we add the wechat for further discussion? Mine is MrSixteen733

**Comment by duan602728596** [comment]
You can modify it by overwriting css, or modify it through the formOptions property

**Comment by jacob2733** [comment]
Thanks, I made this by providing the formOptions. 
` <SchemaForm
      json={json}
      onOk={this.onSubmit}
      okText="ok"
      customComponent={customComponent}
      formOptions={{layout: 'horizontal'}}
    ></SchemaForm>`
