### ISSUE TITLE
About validation error: is not a valid undefined

### ISSUE THREAD

**Issue by mozgbrasil** [duan602728596/antd-schema-form#29]
Good morning my friends

About validation error: is not a valid undefined

I implemented the following project

https://react-berry.vercel.app/react-berry/patients#613253b93d4bfc65cd41156c

We see that even filled the fields, for 2 of these fields a validation error is returned

```
async-validator: ["'$root/properties/dob/properties/age' is not a valid undefined"]
async-validator: ["'$root/properties/registered/properties/age' is not a valid undefined"]
```

If I click on the field, put any character and remove the character I can already go through validation

Thank you in advance if you can help

![Captura de tela de 2021-09-09 19-25-32](https://user-images.githubusercontent.com/17202780/132770672-d660f95f-38ed-44ac-8de5-dd99ce35c720.png)

**Comment by duan602728596** [comment]
I think this problem may be caused by the inconsistency between your value and the type of configuration. The value you pass is of type number, but the form control is of type string. This caused the verification to fail.

**Comment by mozgbrasil** [comment]
Thank you my friend
