### ISSUE TITLE
Hopefully will support dependencies!

### ISSUE THREAD

**Issue by AENeuro** [duan602728596/antd-schema-form#3]
Really appreciate it for writing this up! Hopefully it will support dependencies in the future (like react-jsonschema-form does!)

**Comment by duan602728596** [comment]
Thank you for your support. And what does support dependencies mean? Because I am not very familiar with the react-jsonschema-form.

**Comment by AENeuro** [comment]
So we might have Field A and Field B. 
We might require that the requirement of Field B **depend on** the value of Field A _(eg. If Field A is specified, Field B is required)_. Or we might need Field C to pop up (dynamically) on the occasion that Field A is a specific value.

I thought this is sort of crucial in modern form designing so hopefully can offer you some new ideas.(Can refer to [the doc for dependencies of react-jsonschema-form](https://react-jsonschema-form.readthedocs.io/en/latest/dependencies/) for more info)

**Comment by duan602728596** [comment]
I understand, this is the function of form linkage, I will think about how to achieve this function, thank you for your suggestion.

**Comment by AENeuro** [comment]
加油hhh

**Comment by duan602728596** [comment]
😄hhh
