### ISSUE TITLE
Pass configuration to date-picker

### ISSUE THREAD

**Issue by ericzon** [duan602728596/antd-schema-form#30]
As I see in: https://github.com/duan602728596/antd-schema-form/blob/569cec68cce27938748c334efe0107826e042dd2/src/components/custom/custom.tsx#L59
it seems that right now the date-picker component is forced to always show date. In some cases should be interesting to be able to allow the user only pick a date, without time. How this can be accomplished?

Btw, thank you, good library :)

**Comment by duan602728596** [comment]
ok, i'll take a look at this place.

**Comment by duan602728596** [comment]
Added `$showTime` and `$format` configurations to suit your needs.
