### ISSUE TITLE
componentType date visualization in table

### ISSUE THREAD

**Issue by ericzon** [duan602728596/antd-schema-form#31]
I would like to be able to define a way to configure the visualization of the dates.

I've seen that creating a nested structure like this:

```
{
  id: '$root',
  type: 'object',
  title: 'Form',
  description: "Custom Entity's settings",
  properties: {
    scheduleExceptions: {
      id: '$root/properties/schedule-exceptions',
      type: 'array',
      title: 'Schedule exceptions',
      description: 'List of exceptions aside of default schedule',
      items: {
        id: '$root/properties/schedule-exceptions/items',
        type: 'object',
        title: 'Starting hour',
        description: 'Please fill the starting hour',
        properties: {
          col1: {
            id: '$root/properties/schedule-exceptions/items/properties/col1',
            type: 'string',
            title: 'Day',
            $componentType: 'date',
            $defaultValue: '2010-12-15 08:12:14',
          },
          col2: {
            id: '$root/properties/schedule-exceptions/items/properties/col2',
            type: 'string',
            title: 'From',
            description: 'from desc',
          },
          col3: {
            id: '$root/properties/schedule-exceptions/items/properties/col3',
            type: 'string',
            title: 'To',
            description: 'from desc',
          },
        },
      },
    },
  },
}
```

Generates a table where is not possible to understand the information inside:

 <img width="666" alt="image" src="https://user-images.githubusercontent.com/1809508/162675802-9f98515f-6c02-4968-8976-1e89e4589077.png">

Is there any good approach to improve this?

P.S: As date is a native component of this library, I understand that a solution to display it should be built-in being not necessary to use customComponent.

Thank you

**Comment by duan602728596** [comment]
In this place, in order to save trouble, I displayed the object and array types as their types, and forgot to deal with the moment type. I can modify it.

**Comment by duan602728596** [comment]
Moment objects in tables are now formatted as times.
