### ISSUE TITLE
Custom component for "object" type

### ISSUE THREAD

**Issue by delyanr** [duan602728596/antd-schema-form#4]
This is amazing work! Thanks for publishing.

Any plans to support custom components for the "object" type. I'm looking to create Tabs rather than Collapse for a wizard-like experience.

**Comment by duan602728596** [comment]
I understand, I will try to do this.

**Comment by duan602728596** [comment]
@delyanr It is now possible to create custom components of object type and custom components of oneOf, [reference](https://github.com/duan602728596/antd-schema-form#custom-rendering-component).

**Comment by delyanr** [comment]
Amazing. Thanks so much! I will play around with it. 💯
