### ISSUE TITLE
Import antd components dynamically based on json form schema

### ISSUE THREAD

**Issue by videni** [duan602728596/antd-schema-form#5]
hi, you lib will import lots of antd component even we try to generate a simple form,  because all these components are imported statically, do you have solution for this?

FormObject.tsx
```
import FormString from '../FormString/FormString';
import FormNumber from '../FormNumber/FormNumber';
import FormBoolean from '../FormBoolean/FormBoolean';
import FormArray from '../FormArray/FormArray';
```

**Comment by duan602728596** [comment]
You can use `babel-plugin-import` and configure this in webpack:
```javascript
{
  test: /node_modules[\\/]antd-schema-form$/,
  use: [
      {
        loader: 'babel-loader',
        options: {
          plugins: [
            [
              'import',
              {
                libraryName: 'antd',
                libraryDirectory: 'es',
                style: 'css'
              }
            ]
          ]
        }
      }
    ]
}
```

**Comment by videni** [comment]
@duan602728596 , thanks for you quick response, can you explain why it works ?  as  I know the `babel-plugin-import` is also used for static analysis which runs at compile phrase,  however your library try to build form dynamically which runs at runtime phrase. these components from antd is already imported. I have  json schema form which is quite simple, let's say 3 inputs. these `Form, Tooltip, Input, Select, Radio, DatePicker`  components still will be imported, I don't have DatePicker, Radio, so I hope they won't be included in my bundled js files.

**Comment by duan602728596** [comment]
Sorry, I have misunderstood the problem, and this may not be possible. Because these are all part of my component.

**Comment by videni** [comment]
Maybe we can get all antd components  before we build form.  that is 

1. first, Analyze the JSON form schema, at this step , we can load all related antd components asynchronously at once.

2. then  build  form,  all antd components are already loaded.

**Comment by videni** [comment]
you know at worst case,  all antd components would be loaded even the json form schema is quite simple.

**Comment by duan602728596** [comment]
This may be a way to think about how this should be done better.

**Comment by videni** [comment]
I think this might be the limitation of [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form), it says building form dynamically, but all resources must be loaded first which is not dynamic. it works for desktop application, not for web.

  I  think this for a while, I have a simple solution which might  help.

## Impossible to request several components we find at client side by one request.
the first solution I proposed seems not possible. even though we can find the  AntD components at client side , we can’t request these components by a single request.  For example, we find two components  we need, radio, select, it is not possible to request the two component at once unless they are bundled in one file. the only possible solution is to request  each component one by one. this also is not  good idea.

##  Import components manually before building form.

A form is most likely related to a specific business domain,  so we are pretty sure what components we need , why don’t we just import these components first?  for example, a  form to create product, we know what components will be used before we build form, right?  This solution is quite simple, intuitive and easy to implement.

**Comment by duan602728596** [comment]
This approach can be considered in conjunction with the functionality of a custom component, and components that are now owned are used by custom components.

**Comment by videni** [comment]
@duan602728596 ,  yep,  the `customComponent` property of AntdSchemaFormContext seems like a registry in which we can register custom component,  in the same way, we can also register none custom components too. are you willing to support this feature?

**Comment by duan602728596** [comment]
I can try this weekend, change all components to a custom registration method, separate the components from the rendering.

**Comment by videni** [comment]
@duan602728596 , thank you so much.

**Comment by duan602728596** [comment]
It is ok now.
